name: 🐍 Generate Snake Contribution Grid

on:
  schedule:
    - cron: "0 0 * * *" # every day at midnight
  workflow_dispatch:     # allows manual triggering from GitHub UI

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: generate snake svg
        uses: Platane/snk@v3.3.0
        with:
          github_user_name: vivekmangukiya11
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: push snake svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
