jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: generate-snake-game-from-github-contribution-grid
        uses: Platane/snk@v3.3.0
        with:
          github_user_name: 'vivekmangukiya11'   # your GitHub username here
          github_token: ${{ secrets.GITHUB_TOKEN }}
